---
title: "Untitled"
author: "huanglingling"
date: "2021/8/5"
output: html_document
---

```{r}

req.pcg.install <- function(pcg) {
  new <- pcg[!(pcg %in% installed.packages()[, "Package"])]
  if (length(new))
    
    install.packages(new, dependencies = T,repos 
                     ="http://cran.rstudio.com")
  sapply(pcg, require, ch = T)
  
}
install.pcg <-
  c(
    "readr",
    "readxl",
    "stringr",
    "magrittr",
    "ggplot2",
    "ggpubr",
    "RColorBrewer",
    "rjson"
  )
req.pcg.install(install.pcg)


rm(list = ls())
library(readxl)
library(stringr)
library(plyr)
library(reshape2)
library(ggpubr)
library(RColorBrewer)
library(pheatmap)
library(ggplot2)
library(Rtsne)
library(ggthemes)
library(ggpubr)
library(reshape2)
#install.packages("ggalluvial")
library(ggalluvial)
library(Mfuzz)
options(stringsAsFactors = F)
# BiocManager::install("GSVA")
# BiocManager::install("GSEABase")
library(GSVA)
library(GSEABase)
source("D:/proteomics_library_linda.R")
source("D:/NA_deal.R")

info_all <- read_excel("./CVD_163_new_total.xlsx",sheet = 1)
info_didu <- info_all[,c("number","57d-antiboby","28d-antiboby")]

info_PBMCsample <- read_excel("./CVDHZ_PBMC_MS_info0722.xlsx")
info_Serumsample <- read_excel("./CVDHZ_serum_MS_info0722.xlsx")

info_PBMCsample$`28d-antiboby` <- ifelse(info_PBMCsample$Patient_time=="B",info_didu$`28d-antiboby`[match(info_PBMCsample$Patient_number,info_didu$number)],NA)
info_PBMCsample$`57d-antiboby` <- ifelse(info_PBMCsample$Patient_time=="C",info_didu$`57d-antiboby`[match(info_PBMCsample$Patient_number,info_didu$number)],NA)

table(info_PBMCsample$`28d-antiboby` ) #123:31
table(info_PBMCsample$`57d-antiboby` ) #18:143

info_Serumsample$`28d-antiboby` <- ifelse(info_Serumsample$Patient_time=="B",info_didu$`28d-antiboby`[match(info_Serumsample$Patient_number,info_didu$number)],NA)
info_Serumsample$`57d-antiboby` <- ifelse(info_Serumsample$Patient_time=="C",info_didu$`57d-antiboby`[match(info_Serumsample$Patient_number,info_didu$number)],NA)

table(info_Serumsample$`28d-antiboby` ) #131:32
table(info_Serumsample$`57d-antiboby` ) #19:144

df_PBMC <- read.csv("./20210728CVDHZ_protmatrix_ratio_gene.csv",row.names = 1) 
df_PBMC <- df_PBMC[apply(df_PBMC, 1, function(x) sum(!is.na(x))>0),]
df_PBMCS=df_PBMC[apply(df_PBMC, 1, function(x) {(sum(is.na(x))/length(x)) <0.9}),]
write.csv(df_PBMCS,"df_PBMCS0.9.csv")

linda.summary.matrix(df_PBMC)

linda.plot.density(df_PBMC,outlier = T)

#outlier 值处理
df2.matrix <- as.matrix(df_PBMC)
    outline1 <- (fivenum(df2.matrix)[4]-fivenum(df2.matrix)[2])*2+fivenum(df2.matrix)[4]
    outline2 <- fivenum(df2.matrix)[2]-(fivenum(df2.matrix)[4]-fivenum(df2.matrix)[2])*2
    df2.matrix[df2.matrix>outline1] <- outline1
    df2.matrix[df2.matrix<outline2] <- outline2
linda.plot.density(df2.matrix)

df_PBMC2 <- as.data.frame(df2.matrix) 

```

差异分析：按病人分3类：2个time均免疫，有且仅有一个time免疫，两次都不免疫
```{r 样本分组}
#pbmc
tb=data.frame(Patient_number=info_PBMCsample$Patient_number,didu=apply(info_PBMCsample[,c("28d-antiboby","57d-antiboby")], 1, sum,na.rm=T))
tb2= aggregate(tb[,-c(1)],by = list(tb$Patient_number),sum,na.rm=T)

info_PBMCsample$group= NA

info_PBMCsample$group[info_PBMCsample$Patient_number%in%tb2$Group.1[tb2$x==0]]="group0"
info_PBMCsample$group[info_PBMCsample$Patient_number%in%tb2$Group.1[tb2$x==2]]="group2"
info_PBMCsample$group[info_PBMCsample$Patient_number%in%tb2$Group.1[tb2$x==1]]="group1"
table(info_PBMCsample$group)
# group0 group1 group2 
#     59    341     92 


# info_PBMCsample$group[info_PBMCsample$Patient_number==136]=NA #删28d==1,57d=0的136号样本
# info_PBMCsample$MS_ID[info_PBMCsample$Patient_number==136]

# info_PBMCsample2 = info_PBMCsample[-grep("136",info_PBMCsample$Patient_number),]#删28d==1,57d=0的136号样本
info_PBMCsample2<-info_PBMCsample
df_PBMC3=df_PBMC2[,!names(df_PBMC2)%in%c("C18_4","C18_5","C18_6")]

write.csv(info_PBMCsample,"info_PBMCsample.csv",row.names = F)
# write.csv(info_PBMCsample2,"info_PBMCsample2.csv",row.names = F)
write.csv(df_PBMC3,"df_PBMC3.csv")
```

####FigS3
```{r annova1:同一时间点三group病人样本}
df_PBMC31=df_PBMC3[,na.omit(info_PBMCsample2$MS_ID[info_PBMCsample2$Patient_time=="A"])] #163 #没考虑3个rep样本#163
df_PBMC32=df_PBMC3[,na.omit(info_PBMCsample2$MS_ID[info_PBMCsample2$Patient_time=="B"])]      #154
df_PBMC33=df_PBMC3[,na.omit(info_PBMCsample2$MS_ID[info_PBMCsample2$Patient_time=="C"])]      #161
#################################################ANNOVA##############################################################
#time1-anova
linda.annova2(df_PBMC31,label = info_PBMCsample2$group[match(names(df_PBMC31),info_PBMCsample2$MS_ID)],adjust.p = F,title = "time1_3grouppatient")
#time2-anova
linda.annova2(df_PBMC32,label = info_PBMCsample2$group[match(names(df_PBMC32),info_PBMCsample2$MS_ID)],adjust.p = F,title = "time2_3grouppatient")
#time3-anova
linda.annova2(df_PBMC33,label = info_PBMCsample2$group[match(names(df_PBMC33),info_PBMCsample2$MS_ID)],adjust.p = F,title = "time3_3grouppatient")

#For 3group
differprot1 <- read.csv("./time1_3grouppatient_differprot_pvalue0.05.csv")
differprot1=differprot1[!is.na(differprot1$pvalue),] #430;ad:10
length(differprot1$X[differprot1$adjust.pvalue<0.05])
diffematrix.annova <-  df_PBMC31[differprot1$X[differprot1$adjust.pvalue<0.05],]

differprot2 <- read.csv("./time2_3grouppatient_differprot_pvalue0.05.csv")
differprot2=differprot2[!is.na(differprot2$pvalue),] #319;ad:2
length(differprot2$X[differprot2$adjust.pvalue<0.05])

differprot3 <- read.csv("./time3_3grouppatient_differprot_pvalue0.05.csv")
differprot3=differprot3[!is.na(differprot3$pvalue),] #325;ad:3
length(differprot3$X[differprot3$adjust.pvalue<0.05])

####FigS4:
heatmap.data=df_PBMC3[unique(c(differprot1$X,differprot2$X,differprot3$X)),]
heatmap.data[is.na(heatmap.data)]=0
testdata=data.frame(group=info_PBMCsample2$group[match(names(heatmap.data),info_PBMCsample2$MS_ID)],time=info_PBMCsample2$TIME[match(names(heatmap.data),info_PBMCsample2$MS_ID)],t(heatmap.data))
testdata= aggregate(testdata[,-c(1,2)],by = list(testdata$group,testdata$time),mean)
anncol <- data.frame(testdata[,c(1,2)])
testdata= data.frame(t(testdata[,-c(1,2)]))
names(testdata)=paste0("sample",1:9)
row.names(anncol)=names(testdata)

anncol=data.frame(anncol[order(anncol$Group.1),])
names(anncol)=c("group","time")
testdata=testdata[,row.names(anncol)]

a<-pheatmap(testdata,
         fontsize = 1,
         fontsize_col = 5,
         color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
         annotation_col = anncol,
         scale = "row",
         cluster_rows = T,
         cluster_cols =F,
         show_rownames = T,
         show_colnames = F,
         border = F ,
         filename = "Overlapall.difftime_heatmap_mean_PBMC.pdf",
         main = "",
         height =10,width =5)
```


```{r 0d的三类病人样本去掉验证集再t-test 机器学习特征筛选20210930}
##########################################20210930 只使用training data作ttest特征筛选################################################

#time1-P1 vs P2/P3

info_0d <- info_PBMCsample2[info_PBMCsample2$MS_ID%in%names(df_PBMC31),]
second.info <- read_excel("./two_163data_0918.xlsx")
second.info <- second.info[apply(second.info, 1, function(x) {sum(!is.na(x))>0}),]
info_0d$recruit <- second.info$`Recruitment date ee`[match(info_0d$Patient_number,second.info$`Sample number`)]

matrix_PBMC31.training <- df_PBMC31[,info_0d$MS_ID[info_0d$recruit==1]] #26
matrix_PBMC31.predict <- df_PBMC31[,info_0d$MS_ID[info_0d$recruit==2]] #137

group=info_0d$group[match(names(matrix_PBMC31.training),info_0d$MS_ID)]
group0.sam= names(matrix_PBMC31.training)[grep("group0",group)]#14
group2.sam= names(matrix_PBMC31.training)[grep("group2",group)]#28
group1.sam= names(matrix_PBMC31.training)[grep("group1",group)] #95

##合并P2/P3，time1-P1 vs P2/P3
M4=matrix_PBMC31.training[apply(matrix_PBMC31.training[,group0.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]
M4=M4[apply(M4[,group2.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]
M4=M4[apply(M4[,group1.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]

diff_2group <- linda.volcano.plot(M4,logtransformation = F,group1 = names(M4)%in%c(group2.sam,group1.sam),group2 = names(M4)%in%group0.sam,label1 = "PBMCTime1group12",label2 = "group0.new0930",fold_change = 2^0.25)
length(diff_2group) #dw4:up8


feature = diff_2group

#write.csv(df_PBMC31,"df_PBMC31.csv") #alldata
write.csv(matrix_PBMC31.training[feature,],"df_PBMC31_12feature210930.csv") #traingdata
write.csv(matrix_PBMC31.predict[feature,],"PBMC.predict_12feature210930.csv") #traingdata
write.csv(info_0d,"info_0d.pbmc.csv")

##time1-P1/P2/P3两两比较
M1=M4[,c(group1.sam,group0.sam)]
t1.differprot <- linda.volcano.plot(M1,logtransformation = F,group1 =names(M1)%in%group1.sam ,group2 = names(M1)%in%group0.sam,label1 = "PBMCTime1group1",label2 = "group0.new093",fold_change = 2^0.25)# 11

M2=M4[,c(group2.sam,group0.sam)]
linda.volcano.plot(M2,logtransformation = F,group1 = names(M2)%in%group2.sam,group2 = names(M2)%in%group0.sam,label1 = "PBMCTime1group2",label2 = "group0.new093",fold_change = 2^0.25)
#time1-P2/P3
M3=M4[,c(group2.sam,group1.sam)]
linda.volcano.plot(M3,logtransformation = F,group1 = names(M3)%in%group2.sam,group2 = names(M3)%in%group1.sam,label1 = "PBMCTime1group2",label2 = "group1.new093",fold_change = 2^0.25)
#######2021119 只使用training data作annova特征筛选
#time1-anova
linda.annova2(M4,label = info_0d$group[match(names(M4),info_0d$MS_ID)],adjust.p = F,title = "PBMCtime1_3groupDiff.new093")

```


```{r 同一时间点0d,28d,57d做group12 vs group0的差异筛选 group1 group2无显著差异，合并这两类作t-test}
#################################################df_PBMC31 time1-Ttest#############################################################
group=info_PBMCsample2$group[match(names(df_PBMC31),info_PBMCsample2$MS_ID)]
group0.sam= names(df_PBMC31)[grep("group0",group)]#19
group2.sam= names(df_PBMC31)[grep("group2",group)]#30
group1.sam= names(df_PBMC31)[grep("group1",group)] #114

#time1-P1 vs P2/P3
M4=df_PBMC31[apply(df_PBMC31[,group0.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]
M4=M4[apply(M4[,group2.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]
M4=M4[apply(M4[,group1.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]

diff_2group <- linda.volcano.plot2(M4,logtransformation = F,group1 = names(M4)%in%c(group2.sam,group1.sam),group2 = names(M4)%in%group0.sam,label1 = "Time1group12",label2 = "group0",fold_change = 2^0.25)
length(diff_2group) #16个 "P46783" "P0DJI9" "P06703" "Q9UPU7" "P24723" "P63313" "P52848" "P60604" "P49005" "Q9ULK4" "Q8N841" "Q14517" "O43187" "Q8NAA5" "P30711" "Q9BQ69"
write.csv(diff_2group,"diff_2group.csv",row.names = F)
intersect(diff_2group,t1.differprot) #10个overlap

#################################################df_PBMC32 time2-Ttest#############################################################
group=info_PBMCsample2$group[match(names(df_PBMC32),info_PBMCsample2$MS_ID)]
group0.sam= names(df_PBMC32)[grep("group0",group)]#19
group2.sam= names(df_PBMC32)[grep("group2",group)]#30
group1.sam= names(df_PBMC32)[grep("group1",group)] #105

#合并group12 vs group0
M4=df_PBMC32[apply(df_PBMC32[,group0.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]
M4=M4[apply(M4[,group2.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]
M4=M4[apply(M4[,group1.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]

#time2-P1 vs P2/P3
diff_time2 <- linda.volcano.plot2(M4,logtransformation = F,group1 = names(M4)%in%c(group2.sam,group1.sam),group2 = names(M4)%in%group0.sam,label1 = "Time2group12",label2 = "group0",fold_change = 2^0.25) #19个

######################################df_PBMC33 time3-Ttest没有考虑rep样本#############################################################
group=info_PBMCsample2$group[match(names(df_PBMC33),info_PBMCsample2$MS_ID)]
group0.sam= names(df_PBMC33)[grep("group0",group)]#18
group2.sam= names(df_PBMC33)[grep("group2",group)]#30
group1.sam= names(df_PBMC33)[grep("group1",group)] #113
#合并group12 vs group0
M4=df_PBMC33[apply(df_PBMC33[,group0.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]
M4=M4[apply(M4[,group2.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]
M4=M4[apply(M4[,group1.sam],1,function(x) {sum(is.na(x))/length(x)<0.9}),]

#time3-P1 vs P2/P3
diff_time3 <- linda.volcano.plot2(M4,logtransformation = F,group1 = names(M4)%in%c(group2.sam,group1.sam),group2 = names(M4)%in%group0.sam,label1 = "Time3group12",label2 = "group0",fold_change = 2^0.25) #5个
```


```{r mfuzz：同一group三个时间点病人样本}
df_PBMC41=df_PBMC3[,info_PBMCsample2$MS_ID[info_PBMCsample2$group=="group0"]]
df_PBMC42=df_PBMC3[,info_PBMCsample2$MS_ID[info_PBMCsample2$group=="group2"]]
df_PBMC43=df_PBMC3[,info_PBMCsample2$MS_ID[info_PBMCsample2$group=="group1"]]

data=df_PBMC41
names(data) = info_PBMCsample2$TIME[match(names(df_PBMC41),info_PBMCsample2$MS_ID)]
df.mfu <- aggregate(t(df_PBMC41),by = list(names(data)),mean,na.rm=T)
df.mfu2 <- data.frame(t(df.mfu[,-1]))
names(df.mfu2) <- df.mfu[,1]
set.seed(10)
a <- ge.mfuzz.cselection(df.mfu2,seq(2,12,2))
ge.mfuzz.getresult(a,12,names(df.mfu2),"Group0sample.mfuzz")

data=df_PBMC43
names(data) = info_PBMCsample2$TIME[match(names(df_PBMC43),info_PBMCsample2$MS_ID)]
df.mfu <- aggregate(t(df_PBMC43),by = list(names(data)),mean,na.rm=T)
df.mfu2 <- data.frame(t(df.mfu[,-1]))
names(df.mfu2) <- df.mfu[,1]
set.seed(10)
a <- ge.mfuzz.cselection(df.mfu2,seq(2,12,2))
ge.mfuzz.getresult(a,12,names(df.mfu2),"Group1sample.mfuzz")

data=df_PBMC42
names(data) = info_PBMCsample2$TIME[match(names(df_PBMC42),info_PBMCsample2$MS_ID)]
df.mfu <- aggregate(t(df_PBMC42),by = list(names(data)),mean,na.rm=T)
df.mfu2 <- data.frame(t(df.mfu[,-1]))
names(df.mfu2) <- df.mfu[,1]
set.seed(10)
a <- ge.mfuzz.cselection(df.mfu2,seq(2,12,2))
ge.mfuzz.getresult(a,12,names(df.mfu2),"Group2sample.mfuzz")

```

Fig3B
```{r group12-group0的3个time差异蛋白合并heatmap}

d1 <- read.csv("./Time1group12_group0_all_volcano.csv",row.names = 1) #163
d11 <- d1[abs(d1$log2.foldchange.)>0.25 & d1$P_value_adjust <0.05,]
#d11 <- d1[abs(d1$log2.foldchange.)>0.25 & d1$P_value <0.05,]
d2 <- read.csv("./Time2group12_group0_all_volcano.csv",row.names = 1)#154
d22 <- d2[abs(d2$log2.foldchange.)>0.25 & d2$P_value_adjust <0.05,]
#d22 <- d2[abs(d2$log2.foldchange.)>0.25 & d2$P_value <0.05,]
d3 <- read.csv("./Time3group12_group0_all_volcano.csv",row.names = 1)#161
d33 <- d3[abs(d3$log2.foldchange.)>0.25 & d3$P_value_adjust <0.05,]
#d33 <- d3[abs(d3$log2.foldchange.)>0.25 & d3$P_value <0.05,]
mergePBMC <- rbind(d11[,c("log2.foldchange.","P_value","P_value_adjust")],d22[,c("log2.foldchange.","P_value","P_value_adjust")],d33[,c("log2.foldchange.","P_value","P_value_adjust")])
mergePBMC$group <- c(rep("Time1group12_group0",nrow(d11)),rep("Time2group12_group0",nrow(d22)),rep("Time3group12_group0",nrow(d33)))
write.csv(mergePBMC,"mergePBMC.csv")

#heatmap.data=df_PBMC3[unique(c(row.names(d11),row.names(d22),row.names(d33))),] 差异分析时没有rep样本
heatmap.data=df_PBMC3[unique(c(row.names(d11),row.names(d22),row.names(d33))),
                      c(names(d11),names(d22),names(d33))[!c(names(d11),names(d22),names(d33))%in%c("log2.foldchange.","P_value","P_value_adjust")]]

anncol=data.frame(group=info_PBMCsample2$group[match(names(heatmap.data),info_PBMCsample2$MS_ID)]
                  ,label=info_PBMCsample2$TIME[match(names(heatmap.data),info_PBMCsample2$MS_ID)],
                  row.names = names(heatmap.data))

anncol=data.frame(anncol[order(anncol$group),])

anncol$group <- gsub("group1|group2","group12",anncol$group)

centermatrix <- heatmap.data[,row.names(anncol)]
names(centermatrix) <- paste0(anncol$label,"_",anncol$group)

m2 <- data.frame(type=names(centermatrix),t(centermatrix))

##按照每个时间点的group求平均

m1 <- aggregate(m2[,-1],by = list(m2$type),mean,na.rm=TRUE)

centermatrix2 <- t(data.frame(m1[,-1],row.names = m1$Group.1))

anncol2 <- data.frame(
                  group=rep(c("group0","group12"),3),
                  time=rep(c("time1","time2","time3"),each=2),
                  row.names = unlist(dimnames(centermatrix2)[2]))
anncol2 <- anncol2[order(anncol2$time),]

pdata <- pheatmap(centermatrix2[,row.names(anncol2)],
                  fontsize_col = 7,
         fontsize = 7,
         color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
         annotation_col = anncol2,
         #annotation_row = pathway,
         scale = "row",
         cluster_rows = TRUE,
         cluster_cols =FALSE,
         show_rownames = T,
         show_colnames = FALSE,
         filename = "AlldiffPBMC.meanV1_group12-group0renew.pdf",
        # filename = "AlldiffPBMC_pavlue0.05.meanV1_group12-group0renew.pdf",
         main = ""
        )

 heatmap.prots <- row.names(centermatrix2)[pdata$tree_row[["order"]]]
write.csv( heatmap.prots,"heatmap.prots.csv")

###
node <- read.csv("./PBMCfinal_nodes.csv")
gene_symbol <- unlist(lapply(row.names(df_PBMC), function(x) {str_split(x,"_")[[1]][2]}))

gene_symbol=unlist(lapply(gene_symbol, function(x) {str_split(x,";")[[1]][1]}))
 
prot <- row.names(df_PBMC)[match(node$Symbol,gene_symbol)]

prot[is.na(prot)] = unlist(lapply(c("P82921","P07305","P10412","P06899","P30049"), function(x) row.names(df_PBMC)[grep(x,row.names(df_PBMC))]))
  #paste0(node$Symbol[is.na(match(node$Symbol,gene_symbol))],"_",c("P82921","P07305","P10412","P06899","P30049"))
heatmap.data=df_PBMC3[prot,]


anncol=data.frame(group=info_PBMCsample2$group[match(names(heatmap.data),info_PBMCsample2$MS_ID)]
                  ,label=info_PBMCsample2$TIME[match(names(heatmap.data),info_PBMCsample2$MS_ID)],
                  row.names = names(heatmap.data))

anncol=data.frame(anncol[order(anncol$group),])

anncol$group <- gsub("group1|group2","group12",anncol$group)

centermatrix <- heatmap.data[,row.names(anncol)]
names(centermatrix) <- paste0(anncol$label,"_",anncol$group)

m1  <- data.frame(type=names(centermatrix),t(centermatrix))

##按照每个时间点的group求平均
m1 <- aggregate(m1[,-1],by = list(m1$type),mean,na.rm=T)
centermatrix2 <- t(data.frame(m1[,-1],row.names = m1$Group.1))

anncol2 <- data.frame(
                  group=rep(c("group0","group12"),3),
                  time=rep(c("time1","time2","time3"),each=2),
                  row.names = unlist(dimnames(centermatrix2)[2]))

pheatmap(centermatrix2,
         fontsize = 6,
         color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
         annotation_col = anncol2,
         scale = "row",
         cluster_rows = T,
         cluster_cols =F,
         show_rownames = T,
         show_colnames = F,
         filename = "PBMCnodeprots.mean_group12-group0.pdf",
         main = "",height = 12
        )

####MCODE_CLUSTER_ID 为1，7, 9 画扇形6等分
#node[which(node$MCODE_CLUSTER_ID==1|node$MCODE_CLUSTER_ID==7|node$MCODE_CLUSTER_ID==9),]
node_piegene <- node$Symbol[which(node$MCODE_CLUSTER_ID==1|node$MCODE_CLUSTER_ID==7|node$MCODE_CLUSTER_ID==9)] #34gene
data.node <- centermatrix2[row.names(df_PBMC)[match(node_piegene,gene_symbol)],]
##批量画pie
dir.create("rose_pie")
p <- list()
for (i in 1:nrow(data.node)) {
  data_rose = data.frame(data.node[i,])
colnames(data_rose) <- row.names(data.node)[i]
data_rose$group <- row.names(data_rose)
order_group = c("time1_group0","time2_group0","time3_group0","time3_group12","time2_group12","time1_group12")
data_rose <- data_rose[order_group,]
data_rose$group <- factor(x = data_rose$group,levels =  data_rose$group)

data_rose$label = c(rep("group0",3),rep("group12",3))
data_rose$name = c(c("0d","28d","57d"),c("57d","28d","0d"))

p[[i]] <- ggplot(data_rose, aes(group, get(row.names(data.node)[i]),fill = label)) +
  geom_col(width = 1, size=0.8,#bar的边框线粗细
           color="black") + #画bar 
  #geom_col(aes(y = max(data_rose$P49913_CAMP,na.rm = T)),width = 1, alpha = 0.1, color="black",fill = 'white',size = 0) + #人为加外圈园
  geom_hline(aes(yintercept = max(data_rose[,1],na.rm = T)),size=0.8)+ #外圈园半径是最大值
  geom_col(aes(y = 0.2*min(data_rose[,1],na.rm = T)), width = 1, color = 'white', fill = 'white') + #内圈空心园
   scale_fill_manual(values = c("#377EB8","#FF7F00")) + 
  coord_polar(direction=-1)+#极坐标转换，逆时针排序
  theme_void() +
  theme(legend.position = "none")
# ggsave(paste0(row.names(data.node)[i],"_rose.pdf"),plot = p[[i]],height = 5,width = 5,device = NULL)  
ggsave(paste0("rose_pie/",row.names(data.node)[i],"_rose.pdf"),plot = p[[i]],height = 5,width = 5,device = NULL)  
}

```


```{r boxplot-machine learning的feature}

info_PBMCsample2 <- read.csv("./info_PBMCsample.csv",row.names = 1)
df_PBMC3 <- read.csv("./df_PBMC3.csv",row.names = 1)

feature <- read.csv("./score_and_feature_PBMC(best).csv",row.names = 1)
valiprot_matrix <- data.frame(t(df_PBMC3[names(feature),]),
                              time=info_PBMCsample2$TIME[match(names(df_PBMC3),info_PBMCsample2$MS_ID)],
                              group=info_PBMCsample2$group[match(names(df_PBMC3),info_PBMCsample2$MS_ID)])

valiprot_matrix$group <- gsub("group1|group2","group12",valiprot_matrix$group)

boxdata <-  melt(valiprot_matrix,measure.vars = names(valiprot_matrix)[!grepl("time|group",names(valiprot_matrix))],variable.name = "protein",value.name = "intensity")

boxdata$type <- paste0(boxdata$time,"_",boxdata$group)

my_comparisons <- list(c("time1_group0","time1_group12"))

for (i in unique(boxdata$protein)) {
  data=boxdata[boxdata$protein==i,]
  p <- ggboxplot(data, x = "type", y = "intensity",
                 #color = "Type",
                 fill = "group",width = 0.3,
                 size =0.5,
                 outlier.shape = 19
                 
  )+
    scale_fill_manual(values = c("#377EB8","#FF7F00"))+
    scale_x_discrete(limits=c("time1_group0","time1_group12"))+
    scale_y_log10()+
    labs(title = i)+
    stat_compare_means(comparisons = my_comparisons,
                       hide.ns = F,label="p.signif",
                       method = "t.test"
    )+
    theme(axis.text = element_text(size = 12,colour = "black"),
        text = element_text(size = 10,colour = "black"),#调整label text的字体大小
        axis.title.x = element_text(size = 15,colour = "black")
  )+
  theme(axis.text.x = element_text(hjust = 1,angle = 45))
  
  ggsave(paste0(i,"_boxplot.pdf"),plot = p,width =4,height = 4)
}
#####################################180d的machine learning feture boxplot#############################
feature <- read.csv("./score_and_feature_PBMC2.csv")
second.info <- read_excel("./two_163data_0918.xlsx")
second.info <- second.info[apply(second.info, 1, function(x) {sum(!is.na(x))>0}),]
info_PBMCsample2$`180d-anti` <- second.info$`Seroconversion of Nab j , (180d)` [match(info_PBMCsample2$Patient_number,second.info$`Sample number`)]

info_PBMCsample2$`180d-antigroup` <- ifelse(!is.na(info_PBMCsample2$`180d-anti`),paste0("Group",info_PBMCsample2$`180d-anti`),NA)
info_PBMCsample2$`180d-antigroup` <- gsub("Group0","Group3",info_PBMCsample2$`180d-antigroup`)
info_PBMCsample2$`180d-antigroup` <- gsub("Group1","Group4",info_PBMCsample2$`180d-antigroup`)  

info_PBMCsample2$recruit <- second.info$`Recruitment date ee`[match(info_PBMCsample2$Patient_number,second.info$`Sample number`)]

write.csv(info_PBMCsample2,"info_PBMCsample2_latest.csv")

valiprot_matrix <- data.frame(t(df_PBMC3[match(feature$Prot,linda.split(row.names(df_PBMC3),pattern = "_",character_pos = 1)),]),
                              time=info_PBMCsample2$TIME[match(names(df_PBMC3),info_PBMCsample2$MS_ID)],
                              group=info_PBMCsample2$`180d-antigroup`[match(names(df_PBMC3),info_PBMCsample2$MS_ID)])

valiprot_matrix2 <- valiprot_matrix[!is.na(valiprot_matrix$group),] #439删掉180天没label的样本

length(unique(info_PBMCsample2$Patient_number[info_PBMCsample2$recruit==2])) #删掉26个第二批次

valiprot_matrix3 <- valiprot_matrix2[!row.names(valiprot_matrix2)%in%info_PBMCsample2$MS_ID[info_PBMCsample2$recruit==2],]
valiprot_matrix4 <- valiprot_matrix3[!row.names(valiprot_matrix3)%in%info_PBMCsample2$MS_ID[info_PBMCsample2$group=="group0"],]#删掉group0从来没有抗体的人 left 321samples
write.csv(valiprot_matrix4,"PBMC180d_trainingsamples.csv")

boxdata <-  melt(valiprot_matrix4,measure.vars = names(valiprot_matrix4)[!grepl("time|group",names(valiprot_matrix4))],variable.name = "protein",value.name = "intensity")

boxdata$type <- paste0(boxdata$time,"_",boxdata$group)

my_comparisons <- list(c("time1_Group3","time1_Group4"))

for (i in unique(boxdata$protein)) {
  data=boxdata[boxdata$protein==i,]
  p <-  ggplot(data,aes(x = type, y=intensity,fill = group)) +
    geom_boxplot()+
    stat_boxplot(geom="errorbar", width=0.2) +
    geom_smooth(aes(group=group,color =group),method="loess",se=T,span=0.8, size=0.6,alpha
=0.7,level = 0.95)+
    scale_fill_manual(values = c("#377EB8","#FF7F00"))+
    scale_color_manual(values = c("#377EB8","#FF7F00"))+
    scale_x_discrete(limits=c("time1_Group3","time1_Group4"))+
    scale_y_log10()+
    labs(title = i)+
    stat_compare_means(comparisons = my_comparisons,
                       hide.ns = T,label="p.signif",
                       method = "t.test"
    )+
     theme_classic()+
    theme(axis.text = element_text(size = 10,colour = "black"),
        text = element_text(size = 10,colour = "black"),#调整label text的字体大小
        axis.title.x = element_text(size = 10,colour = "black")
  )+
  theme(axis.text.x = element_text(hjust = 1,angle = 45))+
   theme(panel.grid =element_blank()) +
 theme(axis.ticks = element_blank())
  ggsave(paste0(i,"_boxplot.pdf"),plot = p)
}


```


```{r metascape heatmap}
down <- read_excel("./plot/down_metascape_result.xlsx")
up <- read_excel("./plot/up_metascape_result.xlsx")
dw_up <- read_excel("./plot/PBMC_down_serum_up_metascape_result.xlsx")
up_dw <- read_excel("./plot/PBMC_up_serum_down_metascape_result.xlsx")

info_PBMCsample2 <- read.csv("./info_PBMCsample.csv",row.names = 1)
df_PBMC3 <- read.csv("./df_PBMC3.csv",row.names = 1)


info_Serumsample2 <- read.csv("./serum/info_Serumsample.csv",row.names = 1)
df_serum3 <- read.csv("./serum/df_serum3.csv",row.names = 1)

protlist <- as.character(lapply(row.names(df_PBMC3), function(x) {str_split(x,"_")[[1]][1]}))

############################################1picture
heatmap.data1 <- df_PBMC3[match(down$MyList,protlist),]
heatmap.data2 <- df_serum3[match(down$MyList,as.character(lapply(row.names(df_serum3), function(x) {str_split(x,"_")[[1]][1]}))),]


anncol=data.frame(group=info_PBMCsample2$group[match(names(heatmap.data1),info_PBMCsample2$MS_ID)]
                  ,label=info_PBMCsample2$TIME[match(names(heatmap.data1),info_PBMCsample2$MS_ID)],
                  row.names = names(heatmap.data1))

anncol=data.frame(anncol[order(anncol$group),])

anncol$group <- gsub("group1|group2","group12",anncol$group)

centermatrix <- heatmap.data1[,row.names(anncol)]
names(centermatrix) <- paste0(anncol$label,"_",anncol$group)
#m1 <- data.frame(type=names(centermatrix)[grep("time1",names(centermatrix))],t(centermatrix[,grep("time1",names(centermatrix))]))
m1  <- data.frame(type=names(centermatrix),t(centermatrix))

##按照每个时间点的group求平均
m1 <- aggregate(m1[,-1],by = list(m1$type),mean,na.rm=T)
centermatrix2 <- t(data.frame(m1[,-1],row.names = m1$Group.1))

#serum
anncol2=data.frame(group=info_Serumsample2$group[match(names(heatmap.data2),info_Serumsample2$MS_ID)]
                  ,label=info_Serumsample2$TIME[match(names(heatmap.data2),info_Serumsample2$MS_ID)],
                  row.names = names(heatmap.data2))

anncol2=data.frame(anncol2[order(anncol2$group),])

anncol2$group <- gsub("group1|group2","group12",anncol2$group)

centermatrix <- heatmap.data2[,row.names(anncol2)]
names(centermatrix) <- paste0(anncol2$label,"_",anncol2$group)
#m1 <- data.frame(type=names(centermatrix)[grep("time1",names(centermatrix))],t(centermatrix[,grep("time1",names(centermatrix))]))
m1  <- data.frame(type=names(centermatrix),t(centermatrix))
##按照每个时间点的group求平均
m1 <- aggregate(m1[,-1],by = list(m1$type),mean,na.rm=T)
centermatrix4 <- t(data.frame(m1[,-1],row.names = m1$Group.1))

centermatrix22 <- data.frame(t(scale(t(centermatrix2))))
centermatrix44 <- data.frame(t(scale(t(centermatrix4))))

centermatrix5 <- cbind.data.frame(centermatrix22,centermatrix44)

names(centermatrix5) <- c(paste0("PBMC_",names(centermatrix5)[1:6]),paste0("Serum_",names(centermatrix5)[7:12]))


anncol22 <- data.frame(
                  group=rep(rep(c("group0","group12"),each=3),2),
                  time=rep(c("time1","time2","time3"),2),
                  type=c(rep("PBMC",6),rep("Serum",6))
                  )
row.names(anncol22) <- c(paste0("PBMC_",anncol22$time,"_",anncol22$group)[1:6],paste0("Serum_",anncol22$time,"_",anncol22$group)[7:12])

centermatrix6 <- centermatrix5[,row.names(anncol22)]

annrow=data.frame(down[,c(15:ncol(down))],row.names = down$MyList)

annrow[annrow=="0.0"]=NA
annrow[annrow=="nan"]=NA
#annrow <- as.data.frame(lapply(annrow, as.numeric),row.names =row.names(annrow) )
row.names(annrow) = row.names(centermatrix6)

pdata <- pheatmap(centermatrix6,
        color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
         annotation_col = anncol22,
         annotation_row = annrow,
         #scale = "row",
         cluster_rows = T,
        cluster_cols = FALSE,
        #  show_rownames = T,
        #  show_colnames = F,
          filename = "down_metascape_heatmap2.pdf",
        main = "",width = 12,height = 12,annotation_legend=FALSE
        )

clust.prots_down <- row.names(centermatrix6)[pdata$tree_row[["order"]]]

pheatmap(centermatrix6,
        color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
         annotation_col = anncol22,
         #scale = "row",
         cluster_rows = T,
        cluster_cols = FALSE,
        #  show_rownames = T,
        #  show_colnames = F,
          filename = "down_metascape_heatmap.pdf",
        main = ""
        )
############################################2picture
heatmap.data1 <- df_PBMC3[match(up$MyList,protlist),]
heatmap.data2 <- df_serum3[match(up$MyList,as.character(lapply(row.names(df_serum3), function(x) {str_split(x,"_")[[1]][1]}))),]


anncol=data.frame(group=info_PBMCsample2$group[match(names(heatmap.data1),info_PBMCsample2$MS_ID)]
                  ,label=info_PBMCsample2$TIME[match(names(heatmap.data1),info_PBMCsample2$MS_ID)],
                  row.names = names(heatmap.data1))

anncol=data.frame(anncol[order(anncol$group),])

anncol$group <- gsub("group1|group2","group12",anncol$group)

centermatrix <- heatmap.data1[,row.names(anncol)]
names(centermatrix) <- paste0(anncol$label,"_",anncol$group)
#m1 <- data.frame(type=names(centermatrix)[grep("time1",names(centermatrix))],t(centermatrix[,grep("time1",names(centermatrix))]))
m1  <- data.frame(type=names(centermatrix),t(centermatrix))

##按照每个时间点的group求平均
m1 <- aggregate(m1[,-1],by = list(m1$type),mean,na.rm=T)
centermatrix2 <- t(data.frame(m1[,-1],row.names = m1$Group.1))

#serum
anncol2=data.frame(group=info_Serumsample2$group[match(names(heatmap.data2),info_Serumsample2$MS_ID)]
                  ,label=info_Serumsample2$TIME[match(names(heatmap.data2),info_Serumsample2$MS_ID)],
                  row.names = names(heatmap.data2))

anncol2=data.frame(anncol2[order(anncol2$group),])

anncol2$group <- gsub("group1|group2","group12",anncol2$group)

centermatrix <- heatmap.data2[,row.names(anncol2)]
names(centermatrix) <- paste0(anncol2$label,"_",anncol2$group)
#m1 <- data.frame(type=names(centermatrix)[grep("time1",names(centermatrix))],t(centermatrix[,grep("time1",names(centermatrix))]))
m1  <- data.frame(type=names(centermatrix),t(centermatrix))
##按照每个时间点的group求平均
m1 <- aggregate(m1[,-1],by = list(m1$type),mean,na.rm=T)
centermatrix4 <- t(data.frame(m1[,-1],row.names = m1$Group.1))

centermatrix22 <- data.frame(t(scale(t(centermatrix2))))
centermatrix44 <- data.frame(t(scale(t(centermatrix4))))

centermatrix5 <- cbind.data.frame(centermatrix22,centermatrix44)

names(centermatrix5) <- c(paste0("PBMC_",names(centermatrix5)[1:6]),paste0("Serum_",names(centermatrix5)[7:12]))


anncol22 <- data.frame(
                  group=rep(rep(c("group0","group12"),each=3),2),
                  time=rep(c("time1","time2","time3"),2),
                  type=c(rep("PBMC",6),rep("Serum",6))
                  )
row.names(anncol22) <- c(paste0("PBMC_",anncol22$time,"_",anncol22$group)[1:6],paste0("Serum_",anncol22$time,"_",anncol22$group)[7:12])

centermatrix6 <- centermatrix5[,row.names(anncol22)]

pdata <- pheatmap(centermatrix6,
        color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
         annotation_col = anncol22,
         #scale = "row",
         cluster_rows = T,
        cluster_cols = FALSE,
        #  show_rownames = T,
        #  show_colnames = F,
          filename = "up_metascape_heatmap.pdf",
        main = ""
        )
clust.prots_up <-  row.names(centermatrix6)[pdata$tree_row[["order"]]]

annrow=data.frame(up[,c(15:ncol(up))],row.names = up$MyList)

annrow[annrow=="0"]=NA
annrow[annrow=="nan"]=NA
#annrow <- as.data.frame(lapply(annrow, as.numeric),row.names =row.names(annrow) )
row.names(annrow) = row.names(centermatrix6)

 pheatmap(centermatrix6,
        color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
         annotation_col = anncol22,
         annotation_row = annrow,
         #scale = "row",
         cluster_rows = T,
        cluster_cols = FALSE,
        #  show_rownames = T,
        #  show_colnames = F,
          filename = "up_metascape_heatmap2.pdf",
        main = "",width = 12,height = 12,annotation_legend=FALSE
        )
############################################3picture
heatmap.data1 <- df_PBMC3[match(dw_up$MyList,protlist),]
heatmap.data2 <- df_serum3[match(dw_up$MyList,as.character(lapply(row.names(df_serum3), function(x) {str_split(x,"_")[[1]][1]}))),]


anncol=data.frame(group=info_PBMCsample2$group[match(names(heatmap.data1),info_PBMCsample2$MS_ID)]
                  ,label=info_PBMCsample2$TIME[match(names(heatmap.data1),info_PBMCsample2$MS_ID)],
                  row.names = names(heatmap.data1))

anncol=data.frame(anncol[order(anncol$group),])

anncol$group <- gsub("group1|group2","group12",anncol$group)

centermatrix <- heatmap.data1[,row.names(anncol)]
names(centermatrix) <- paste0(anncol$label,"_",anncol$group)
#m1 <- data.frame(type=names(centermatrix)[grep("time1",names(centermatrix))],t(centermatrix[,grep("time1",names(centermatrix))]))
m1  <- data.frame(type=names(centermatrix),t(centermatrix))

##按照每个时间点的group求平均
m1 <- aggregate(m1[,-1],by = list(m1$type),mean,na.rm=T)
centermatrix2 <- t(data.frame(m1[,-1],row.names = m1$Group.1))

#serum
anncol2=data.frame(group=info_Serumsample2$group[match(names(heatmap.data2),info_Serumsample2$MS_ID)]
                  ,label=info_Serumsample2$TIME[match(names(heatmap.data2),info_Serumsample2$MS_ID)],
                  row.names = names(heatmap.data2))

anncol2=data.frame(anncol2[order(anncol2$group),])

anncol2$group <- gsub("group1|group2","group12",anncol2$group)

centermatrix <- heatmap.data2[,row.names(anncol2)]
names(centermatrix) <- paste0(anncol2$label,"_",anncol2$group)
#m1 <- data.frame(type=names(centermatrix)[grep("time1",names(centermatrix))],t(centermatrix[,grep("time1",names(centermatrix))]))
m1  <- data.frame(type=names(centermatrix),t(centermatrix))
##按照每个时间点的group求平均
m1 <- aggregate(m1[,-1],by = list(m1$type),mean,na.rm=T)
centermatrix4 <- t(data.frame(m1[,-1],row.names = m1$Group.1))

centermatrix22 <- data.frame(t(scale(t(centermatrix2))))
centermatrix44 <- data.frame(t(scale(t(centermatrix4))))

centermatrix5 <- cbind.data.frame(centermatrix22,centermatrix44)

names(centermatrix5) <- c(paste0("PBMC_",names(centermatrix5)[1:6]),paste0("Serum_",names(centermatrix5)[7:12]))


anncol22 <- data.frame(
                  group=rep(rep(c("group0","group12"),each=3),2),
                  time=rep(c("time1","time2","time3"),2),
                  type=c(rep("PBMC",6),rep("Serum",6))
                  )
row.names(anncol22) <- c(paste0("PBMC_",anncol22$time,"_",anncol22$group)[1:6],paste0("Serum_",anncol22$time,"_",anncol22$group)[7:12])

centermatrix6 <- centermatrix5[,row.names(anncol22)]

pdata <- pheatmap(centermatrix6,
        color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
         annotation_col = anncol22,
         #scale = "row",
         cluster_rows = T,
        cluster_cols = FALSE,
        #  show_rownames = T,
        #  show_colnames = F,
          filename = "dw_up_metascape_heatmap.pdf",
        main = ""
        )
clust.prots_dw_up <-  row.names(centermatrix6)[pdata$tree_row[["order"]]]

annrow=data.frame(dw_up[,c(15:ncol(dw_up))],row.names = dw_up$MyList)

annrow[annrow=="0.0"]=NA
annrow[annrow=="nan"]=NA
#annrow <- as.data.frame(lapply(annrow, as.numeric),row.names =row.names(annrow) )
row.names(annrow) = row.names(centermatrix6)

pheatmap(centermatrix6,
        color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
         annotation_col = anncol22,
         annotation_row = annrow,
         #scale = "row",
         cluster_rows = T,
        cluster_cols = FALSE,
        #  show_rownames = T,
        #  show_colnames = F,
          filename = "dw_up_metascape_heatmap2.pdf",
        main = "",width = 12,height = 12,annotation_legend=FALSE
        )
############################################4picture
heatmap.data1 <- df_PBMC3[match(up_dw$MyList,protlist),]
heatmap.data2 <- df_serum3[match(up_dw$MyList,as.character(lapply(row.names(df_serum3), function(x) {str_split(x,"_")[[1]][1]}))),]


anncol=data.frame(group=info_PBMCsample2$group[match(names(heatmap.data1),info_PBMCsample2$MS_ID)]
                  ,label=info_PBMCsample2$TIME[match(names(heatmap.data1),info_PBMCsample2$MS_ID)],
                  row.names = names(heatmap.data1))

anncol=data.frame(anncol[order(anncol$group),])

anncol$group <- gsub("group1|group2","group12",anncol$group)

centermatrix <- heatmap.data1[,row.names(anncol)]
names(centermatrix) <- paste0(anncol$label,"_",anncol$group)
#m1 <- data.frame(type=names(centermatrix)[grep("time1",names(centermatrix))],t(centermatrix[,grep("time1",names(centermatrix))]))
m1  <- data.frame(type=names(centermatrix),t(centermatrix))

##按照每个时间点的group求平均
m1 <- aggregate(m1[,-1],by = list(m1$type),mean,na.rm=T)
centermatrix2 <- t(data.frame(m1[,-1],row.names = m1$Group.1))

#serum
anncol2=data.frame(group=info_Serumsample2$group[match(names(heatmap.data2),info_Serumsample2$MS_ID)]
                  ,label=info_Serumsample2$TIME[match(names(heatmap.data2),info_Serumsample2$MS_ID)],
                  row.names = names(heatmap.data2))

anncol2=data.frame(anncol2[order(anncol2$group),])

anncol2$group <- gsub("group1|group2","group12",anncol2$group)

centermatrix <- heatmap.data2[,row.names(anncol2)]
names(centermatrix) <- paste0(anncol2$label,"_",anncol2$group)
#m1 <- data.frame(type=names(centermatrix)[grep("time1",names(centermatrix))],t(centermatrix[,grep("time1",names(centermatrix))]))
m1  <- data.frame(type=names(centermatrix),t(centermatrix))
##按照每个时间点的group求平均
m1 <- aggregate(m1[,-1],by = list(m1$type),mean,na.rm=T)
centermatrix4 <- t(data.frame(m1[,-1],row.names = m1$Group.1))

centermatrix22 <- data.frame(t(scale(t(centermatrix2))))
centermatrix44 <- data.frame(t(scale(t(centermatrix4))))

centermatrix5 <- cbind.data.frame(centermatrix22,centermatrix44)

names(centermatrix5) <- c(paste0("PBMC_",names(centermatrix5)[1:6]),paste0("Serum_",names(centermatrix5)[7:12]))


anncol22 <- data.frame(
                  group=rep(rep(c("group0","group12"),each=3),2),
                  time=rep(c("time1","time2","time3"),2),
                  type=c(rep("PBMC",6),rep("Serum",6))
                  )
row.names(anncol22) <- c(paste0("PBMC_",anncol22$time,"_",anncol22$group)[1:6],paste0("Serum_",anncol22$time,"_",anncol22$group)[7:12])

centermatrix6 <- centermatrix5[,row.names(anncol22)]

annrow=data.frame(up_dw[,c(15:ncol(up_dw))],row.names = up_dw$MyList)

annrow[annrow=="0"]=NA
annrow[annrow=="nan"]=NA
#annrow <- as.data.frame(lapply(annrow, as.numeric),row.names =row.names(annrow) )
row.names(annrow) = row.names(centermatrix6)

pdata <- pheatmap(centermatrix6,
        color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
         annotation_col = anncol22,
         annotation_row = annrow,
         #scale = "row",
         cluster_rows = T,
        cluster_cols = FALSE,
        #  show_rownames = T,
        #  show_colnames = F,
          filename = "up_dw_metascape_heatmap2.pdf",
        main = "",width = 12,height = 12,annotation_legend=FALSE
        )
clust.prots_up_dw <-  row.names(centermatrix6)[pdata$tree_row[["order"]]]

# DATA <- centermatrix6[,1:2]
# pheatmap(DATA,
#         color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
#         # annotation_col = anncol22,
#          annotation_row = annrow,
#          #scale = "row",
#         cluster_rows = FALSE,
#         cluster_cols = FALSE,
#         #  show_rownames = T,
#         #  show_colnames = F,
#           filename = "up_dw_pathway_heatmap.pdf",
#         main = "",width = 15
#         )
```



```{r 桑基图}
down <- read_excel("./plot/down_metascape_result.xlsx")
up <- read_excel("./plot/up_metascape_result.xlsx")
dw_up <- read_excel("./plot/PBMC_down_serum_up_metascape_result.xlsx")
up_dw <- read_excel("./plot/PBMC_up_serum_down_metascape_result.xlsx")

###picture1 down
san1 <- down[,grep("R-HSA-6798695|R-HSA-114608|GO:0034368|WP2806",names(down))]
san1$prot <- down$MyList
san1 <- san1[match(as.character(lapply(clust.prots_down, function(x) {str_split(x,"_")[[1]][1]})),san1$prot),]

san2 <- melt(san1,measure.vars = names(san1)[-ncol(san1)],variable.name = "Pathway",value.name = "value")
san2$value[san2$value=="0.0"]=NA
san2$value[san2$value=="nan"]=NA
#san3 <- san2[!is.na(san2$value),]
# san2$Pathway[is.na(san2$value)]=NULL
san2$value[san2$Pathway=="WP2806 Complement system" & !is.na(san2$value)]=2
san2$value[is.na(san2$value)]=0
san2$prot <- factor(san2$prot,labels = san2$prot,levels = san2$prot)

p <- ggplot(data = san2,
aes(axis1 = prot, axis2 = Pathway) )+
 scale_x_discrete(limits = c("prot", "Pathway"), expand = c(.1, .05)) +
geom_alluvium(aes(fill = factor(value))) +
geom_stratum() + 
geom_text(stat="stratum",
           aes(label = after_stat(stratum)) #按照data的factor顺序label
           #infer.label = TRUE, reverse = FALSE
          ) + 
theme_minimal() +
 scale_fill_manual(values=c("White","#0F2C67","#CD1818"))+
 theme(panel.grid =element_blank()) +
theme(axis.text.y = element_blank()) +
 theme(axis.ticks = element_blank())
 ggsave(paste0("down_pathway","_alluvial.pdf"),plot=p,width=10,height=8)
##############pic2
san1 <- up[,grep("R-HSA-6798695|R-HSA-114608|GO:0034368|WP2806",names(up))]
san1$prot <- up$MyList
san1 <- san1[match(as.character(lapply(clust.prots_up, function(x) {str_split(x,"_")[[1]][1]})),san1$prot),]

san2 <- melt(san1,measure.vars = names(san1)[-ncol(san1)],variable.name = "Pathway",value.name = "value")

san2$prot <- factor(san2$prot,labels = san2$prot,levels = san2$prot)

p <- ggplot(data = san2,
aes(axis1 = prot, axis2 = Pathway) )+
 scale_x_discrete(limits = c("prot", "Pathway"), expand = c(.1, .05)) +
geom_alluvium(aes(fill = factor(value))) +
geom_stratum() + 
geom_text(stat="stratum",
           aes(label = after_stat(stratum)) #按照data的factor顺序label
           #infer.label = TRUE, reverse = FALSE
          ) + 
theme_minimal() +
 scale_fill_manual(values=c("White","#F3950D"))+
 theme(panel.grid =element_blank()) +
theme(axis.text.y = element_blank()) +
 theme(axis.ticks = element_blank())
 ggsave(paste0("up_pathway","_alluvial.pdf"),plot=p,width=10,height=8)
#############pic3
 san1 <- dw_up[,grep("R-HSA-6798695|R-HSA-114608|GO:0034368|WP2806",names(dw_up))]
san1$prot <- dw_up$MyList
san1 <- san1[match(as.character(lapply(clust.prots_dw_up, function(x) {str_split(x,"_")[[1]][1]})),san1$prot),]

san2 <- melt(san1,measure.vars = names(san1)[-ncol(san1)],variable.name = "Pathway",value.name = "value")
san2$value[san2$value=="0.0"]=NA
san2$value[san2$value=="nan"]=NA
san2$value2 <- as.numeric(as.factor(san2$Pathway))
san2$value[!is.na(san2$value)]=san2$value2[!is.na(san2$value)]
san2$prot <- factor(san2$prot,labels = san2$prot,levels = san2$prot)
san2$value[is.na(san2$value)]=0

p <- ggplot(data = san2,
aes(axis1 = prot, axis2 = Pathway) )+
 scale_x_discrete(limits = c("prot", "Pathway"), expand = c(.1, .05)) +
geom_alluvium(aes(fill = factor(value))) +
geom_stratum() + 
geom_text(stat="stratum",
           aes(label = after_stat(stratum)) #按照data的factor顺序label
           #infer.label = TRUE, reverse = FALSE
          ) + 
theme_minimal() +
 scale_fill_manual(values=c("White","#F4E185","#F3950D","#0F2C67"))+   
 theme(panel.grid =element_blank()) +
theme(axis.text.y = element_blank()) +
 theme(axis.ticks = element_blank())
 ggsave(paste0("dw_up_pathway","_alluvial.pdf"),plot=p,width=10,height=8)
 
 ###########
 san1 <- up_dw[,grep("R-HSA-6798695|R-HSA-114608|GO:0034368|WP2806",names(up_dw))]
san1$prot <- up_dw$MyList
san1 <- san1[match(as.character(lapply(clust.prots_up_dw, function(x) {str_split(x,"_")[[1]][1]})),san1$prot),]

san2 <- melt(san1,measure.vars = names(san1)[-ncol(san1)],variable.name = "Pathway",value.name = "value")
san2$value[san2$value=="0.0"]=NA
san2$value[san2$value=="nan"]=NA

san2$prot <- factor(san2$prot,labels = san2$prot,levels = san2$prot)

p <- ggplot(data = san2,
aes(axis1 = prot, axis2 = Pathway) )+
 scale_x_discrete(limits = c("prot", "Pathway"), expand = c(.1, .05)) +
geom_alluvium(aes(fill = factor(value))) +
geom_stratum() + 
geom_text(stat="stratum",
           aes(label = after_stat(stratum)) #按照data的factor顺序label
           #infer.label = TRUE, reverse = FALSE
          ) + 
theme_minimal() +
 scale_fill_manual(values=c("White","#F3950D"))+
 theme(panel.grid =element_blank()) +
theme(axis.text.y = element_blank()) +
 theme(axis.ticks = element_blank())
 ggsave(paste0("up_dw_pathway","_alluvial.pdf"),plot=p,width=10,height=8)

#######modify on 20211207 up和up_dw合并,down和dw_up合并成2张图画
 ###picture1 down和dw_up
san1 <- down[,grep("R-HSA-6798695|R-HSA-114608|GO:0034368|WP2806",names(down))]
san1$prot <- down$MyList
san1 <- san1[match(as.character(lapply(clust.prots_down, function(x) {str_split(x,"_")[[1]][1]})),san1$prot),]

san2 <- melt(san1,measure.vars = names(san1)[-ncol(san1)],variable.name = "Pathway",value.name = "value")
san2$value[san2$value=="0.0"]=NA
san2$value[san2$value=="nan"]=NA

san11 <- dw_up[,grep("R-HSA-6798695|R-HSA-114608|GO:0034368|WP2806",names(dw_up))]
san11$prot <- dw_up$MyList
san11 <- san11[match(as.character(lapply(clust.prots_dw_up, function(x) {str_split(x,"_")[[1]][1]})),san11$prot),]
san22 <- melt(san11,measure.vars = names(san11)[-ncol(san11)],variable.name = "Pathway",value.name = "value")
san22$value[san22$value=="0.0"]=NA
san22$value[san22$value=="nan"]=NA

san23 <- rbind(san2,san22)

san23$value2 <- as.numeric(as.factor(san23$Pathway))

san23$value[!is.na(san23$value)]=san23$value2[!is.na(san23$value)]

san23$prot <- factor(san23$prot,labels = san23$prot,levels = san23$prot)

san24 <- san23
san24 <- san24[c(grep("WP2806 Complement system",san24$Pathway),
                 grep("R-HSA-6798695 Neutrophil degranulation",san24$Pathway),
                 grep("R-HSA-114608 Platelet degranulation",san24$Pathway),
                 grep("GO:0034368 protein-lipid complex remodeli",san24$Pathway)),]
san24$value[is.na(san24$value)]=0



p <- ggplot(data = san24,
aes(axis1 = prot, axis2 = Pathway) )+
 scale_x_discrete(limits = c("prot", "Pathway"), expand = c(.1, .05)) +
geom_alluvium(aes(fill = factor(value))) +
geom_stratum() + 
geom_text(stat="stratum",
           aes(label = after_stat(stratum)), #按照data的factor顺序label
          size=5
           #infer.label = TRUE, reverse = FALSE
          ) + 
theme_minimal() +
 scale_fill_manual(values=c("White","#0F2C67","#CD1818","#F4E185","#F3950D"))+
 theme(panel.grid =element_blank()) +
theme(axis.text.y = element_blank()) +
 theme(axis.ticks = element_blank())
 ggsave(paste0("BD_pathway","_alluvial.pdf"),plot=p,width=16,height=18)
###picture2 up和up_dw
san1 <- up[,grep("R-HSA-6798695|R-HSA-114608|GO:0034368|WP2806",names(up))]
san1$prot <- up$MyList
san1 <- san1[match(as.character(lapply(clust.prots_up, function(x) {str_split(x,"_")[[1]][1]})),san1$prot),]

san2 <- melt(san1,measure.vars = names(san1)[-ncol(san1)],variable.name = "Pathway",value.name = "value")

san11 <- up_dw[,grep("R-HSA-6798695|R-HSA-114608|GO:0034368|WP2806",names(up_dw))]
san11$prot <- up_dw$MyList
san11 <- san11[match(as.character(lapply(clust.prots_up_dw, function(x) {str_split(x,"_")[[1]][1]})),san11$prot),]
san22 <- melt(san11,measure.vars = names(san11)[-ncol(san11)],variable.name = "Pathway",value.name = "value")
san22$value[san22$value=="0.0"]=NA
san22$value[san22$value=="nan"]=NA

san23 <- rbind(san2,san22)

san23$value2 <- as.numeric(as.factor(san23$Pathway))

san24 <- rbind(data.frame(prot=san23$prot,Pathway=rep("WP2806 Complement 
                                                    system",length(san23$prot)),value=rep("0",length(san23$prot)),value2=rep("0",length(san23$prot))),
               data.frame(prot=san23$prot,Pathway=rep("R-HSA-114608 Platelet 
                                                      degranulation",length(san23$prot)),value=rep("0",length(san23$prot)),value2=rep("0",length(san23$prot))),
               data.frame(prot=san23$prot,Pathway=rep("GO:0034368 protein-lipid complex 
                                                           remodeli",length(san23$prot)),value=rep("0",length(san23$prot)),value2=rep("0",length(san23$prot))),
               san23)

san24$prot <- factor(san24$prot,labels = san24$prot,levels = san24$prot)
san24$Pathway <- factor(san24$Pathway,labels = san24$Pathway,levels = san24$Pathway)

p <- ggplot(data = san24,
aes(axis1 = prot, axis2 = Pathway) )+
 scale_x_discrete(limits = c("prot", "Pathway"), expand = c(.1, .05)) +
geom_alluvium(aes(fill = factor(value))) +
geom_stratum() + 
geom_text(stat="stratum",
           aes(label = after_stat(stratum)), #按照data的factor顺序label
          size=5
           #infer.label = TRUE, reverse = FALSE
          ) + 
theme_minimal() +
 scale_fill_manual(values=c("White","#F3950D","#F4E185","#CD1818","#0F2C67"))+
 theme(panel.grid =element_blank()) +
theme(axis.text.y = element_blank()) +
 theme(axis.ticks = element_blank())
 ggsave(paste0("AC_pathway","_alluvial.pdf"),plot=p,width=18,height=18)
 
```


```{r 预测180天有无抗体的特征筛选：180d有无抗体的t-test（用0d的group12样本且去掉批次2的26个病人（验证集），180d的有无抗体作为label}

# info_0d <- read.csv("./info_0d.pbmc.csv") #0d的163个样本信息
# matrix_PBMC31.training <- df_PBMC31[,info_0d$MS_ID[info_0d$recruit==1]] #137 去掉批次2的26个病人
# 
# second.info <- read_excel("./serum/newmatrix_analysis/two_163data_0918.xlsx")
# second.info <- second.info[apply(second.info, 1, function(x) {sum(!is.na(x))>0}),]
# info_0d$`180d-anti` <- second.info$`Seroconversion of Nab j , (180d)` [match(info_0d$Patient_number,second.info$`Sample number`)]
# 
# mat <- matrix_PBMC31.training
# 
# mat2 <- mat[,!names(mat)%in%info_0d$MS_ID[info_0d$group=="group0"]] #123samples 去掉group0的样本
# 
# mat3 <- data.frame(t(mat2))
# 
# mat3$label <- info_0d$`180d-anti`[match(row.names(mat3),info_0d$MS_ID)]
# 
# mat4 <- mat3[!is.na(mat3$label),] #107samples,删掉180天没label的样本
# 
# table(mat4$label) #77:30
# 
# mat5 <- data.frame(t(mat4[,-grep("label",names(mat4))]))
# 
# NA_threshold_table(mat5)
# mat41 <- mat5[apply(mat5, 1, function(x) {(sum(is.na(x))/length(x)) <0.9}),] #6394prots
# 
# 
# write.csv(mat4,"PBMC_180dfeature_Ttest.rawmat.csv")
# 
# DIFFPROTS0 <- linda.volcano.plot2(mat41,logtransformation = F,group1 = grep("1",mat4$label),group2 = grep("0",mat4$label),label1 = "PBMC_180dGroup4_response1",label2 = "Group3_response0",P.adjust = F,fold_change = 2^0.25)

```


```{r 预测180天有无抗体的特征筛选：180d有无抗体的t-test（用28d/57d的group12样本且去掉批次2的26个病人（验证集），180d的有无抗体作为label}
#############57d
info_57d <- info_PBMCsample2[info_PBMCsample2$MS_ID%in%names(df_PBMC33),]#161
info_57d$recruit <- second.info$`Recruitment date ee`[match(info_57d$Patient_number,second.info$`Sample number`)]
info_57d$`180d-anti` <- second.info$`Seroconversion of Nab j , (180d)` [match(info_57d$Patient_number,second.info$`Sample number`)]

mat <- df_PBMC33[,info_57d$MS_ID[info_57d$recruit==1]] #135 去掉批次2的26个病人

mat2 <- mat[,!names(mat)%in%info_57d$MS_ID[info_57d$group=="group0"]] #122samples 去掉group0的样本

mat3 <- data.frame(t(mat2))

mat3$label <- info_57d$`180d-anti`[match(row.names(mat3),info_57d$MS_ID)]

mat4 <- mat3[!is.na(mat3$label),] #107samples,删掉180天没label的样本

table(mat4$label) #77:30

mat5 <- data.frame(t(mat4[,-grep("label",names(mat4))]))

NA_threshold_table(mat5)
mat41 <- mat5[apply(mat5, 1, function(x) {(sum(is.na(x))/length(x)) <0.9}),] #6394prots*107samples

write.csv(mat4,"PBMC_180dfeature_57dsamTtest.rawmat.csv")

DIFFPROTS0 <- linda.volcano.plot2(mat41,logtransformation = F,group1 = grep("1",mat4$label),group2 = grep("0",mat4$label),label1 = "PBMC_180dGroup4_57d_response1",label2 = "Group3_response0",P.adjust = F,fold_change = 2^0.25)
#############两类病人在57d的蛋白与0d的蛋白变化的比值差异
##57d的矩阵
matrix_57d <- mat41 #6394prots*107samples

#0d的矩阵
info_0d <- read.csv("./info_0d.pbmc.csv") #0d的163个样本信息
matrix_PBMC31.training <- df_PBMC31[,info_0d$MS_ID[info_0d$recruit==1]] #137 去掉批次2的26个病人
info_0d$`180d-anti` <- second.info$`Seroconversion of Nab j , (180d)` [match(info_0d$Patient_number,second.info$`Sample number`)]
mat <- matrix_PBMC31.training
mat2 <- mat[,!names(mat)%in%info_0d$MS_ID[info_0d$group=="group0"]] #123samples 去掉group0的样本
mat3 <- data.frame(t(mat2))
mat3$label <- info_0d$`180d-anti`[match(row.names(mat3),info_0d$MS_ID)]
mat4 <- mat3[!is.na(mat3$label),] #107samples,删掉180天没label的样本
table(mat4$label) #77:30
mat5 <- data.frame(t(mat4[,-grep("label",names(mat4))]))
mat41 <- mat5[apply(mat5, 1, function(x) {(sum(is.na(x))/length(x)) <0.9}),] #6394prots*107samples
matrix_0d <- mat41 

identical(info_PBMCsample2$Patient_number[match(names(matrix_57d),info_PBMCsample2$MS_ID)],
          info_PBMCsample2$Patient_number[match(names(matrix_0d),info_PBMCsample2$MS_ID)])
identical(row.names(matrix_57d),row.names(matrix_0d))

#rate <- log2(matrix_57d/matrix_0d)
rate <- matrix_57d/matrix_0d
names(rate) <- paste0("P",info_PBMCsample2$Patient_number[match(names(matrix_57d),info_PBMCsample2$MS_ID)])

write.csv(t(rate),"PBMC_ratio.csv")
 
sdd <- as.data.frame(apply(rate, 2, sd,na.rm=T))
boxplot(sdd) #怎么直观标记箱线图上的异常值是哪个样本点？2.264249 
out_sample <- row.names(sdd)[sdd>fivenum(unlist(sdd))[4]+1.5*IQR(as.numeric(unlist(sdd)))] #"P155" "P117" "P134" "P192" "P68"  "P178" "P175" "P3"   "P4"   "P55"  "P9"  
View(rate[,out_sample])

O1 <- fivenum(rate)[4]+2*IQR(as.numeric(unlist(rate)),na.rm = T)#2.4
O2 <- fivenum(rate)[2]-2*IQR(as.numeric(unlist(rate)),na.rm = T)#-0.21

rate[rate>O1]=O1
rate[rate<O2]=O2

plot(density(unlist(rate),na.rm=T))#接近正态

antilabel <- info_57d$`180d-anti`[match(names(matrix_57d),info_57d$MS_ID)]

DIFFPROTS0 <- linda.volcano.plot2(rate,logtransformation = F,group1 = grep("1",antilabel),group2 = grep("0",antilabel),label1 = "PBMC_180dGroup4_57-0rate_response1",label2 = "Group3_response0",P.adjust = F,fold_change = 2^0.25)

```

Fig3C
```{r GSEA}
##### 加载GSEA文件 下载地址http://www.gsea-msigdb.org/gsea/msigdb/index.jsp

############全蛋白矩阵的GSVA
df_PBMCS <- read.csv("./df_PBMCS0.9.csv",row.names = 1)

CP<- getGmt("D:/c2.cp.v7.4.symbols.gmt")
# data 行是蛋白，列是样本  需要转换成geneName
gm <- linda.split(row.names(df_PBMCS),character_pos = 2)
gm <- linda.split(gm,pattern = ";",character_pos = 1)
expre <- df_PBMCS
expre$gene <- gm
expre <- expre[gm!="NA",]
expre2 <- expre[!duplicated(expre$gene),]

expre3 <- as.matrix(data.frame(expre2[,-ncol(expre2)],row.names = expre2$gene))
expre30 <- expre3
names<-rownames(expre30)
# expre[1,1]
# expre2[1,1]
# expre3[1,1]
# expre30[1]
exp4 <- gsva(expre30,method="ssgsea",CP, kcdf = "Gaussian", min.sz = 5)

# write.csv(exp1,"exp1_hallmark.csv")
# write.csv(exp2,"exp2_immun.csv")
# write.csv(exp3,"exp3_singlecell.csv")
write.csv(exp4,"exp4_cp.csv")
##################################################canioal KEGG
exp4 <- read.csv("./exp4_cp.csv",row.names = 1)
label <- info_PBMCsample2$group[match(unlist(dimnames(exp4)[2]),info_PBMCsample2$MS_ID)]
label2 <- info_PBMCsample2$`180d-antigroup`[match(unlist(dimnames(exp4)[2]),info_PBMCsample2$MS_ID)]
exp42 <- exp4[,!is.na(label2)] 
label22 <- info_PBMCsample2$`180d-antigroup`[match(unlist(dimnames(exp42)[2]),info_PBMCsample2$MS_ID)]

df1 <- as.data.frame(exp4) #须是data.frame
group1 = !grepl("group0",label)
group2 = grepl("group0",label)

df1$`log2(foldchange)` <- as.numeric(apply(df1,1, function(x) log2(abs((mean(x[group1],na.rm = T)/mean(x[group2],na.rm = T))))))#取绝对值，可能有比值为负的情况
  
  P_value <- apply(df1,
                   1,
                   function(y) {
                     
                     p_try = tryCatch(t.test(y[group1],
                                             y[group2],
                                             paired = F,
                                             var.equal = F)$p.value,
                                      error = function(x) NA)
                   })  
  
  #给data增加p-value列
  df1$P_value<- P_value
  df1$P_value_adjust<-p.adjust(df1$P_value, method="BH")
  up <- subset(df1, df1$P_value_adjust < 0.05 & df1$`log2(foldchange)` > 0.25)
  down <- subset(df1, df1$P_value_adjust < 0.05 & df1$`log2(foldchange)` < -0.25)

diff_pathway <- rbind(up,down)
  
diff_pathway2 <- diff_pathway[,-c((ncol(diff_pathway)-2):ncol(diff_pathway))]
  
anncol <- data.frame(group=info_PBMCsample2$group[match(names(diff_pathway2),info_PBMCsample2$MS_ID)],time=info_PBMCsample2$TIME[match(names(diff_pathway2),info_PBMCsample2$MS_ID)],sample = names(diff_pathway2))
anncol <- anncol[order(anncol$group,anncol$time),]
anncol <- data.frame(anncol[,1:2],row.names = anncol$sample)
  
diff_pathway2 <- diff_pathway2[,row.names(anncol)]
  fivenum(unlist(diff_pathway2))
write.csv(diff_pathway2,"pbmc_diffpathway_CP.csv")

set.seed(1)
pheatmap(diff_pathway2,
         fontsize_col = 7,
         fontsize = 7,
          color = c(brewer.pal(11,"RdYlBu")[11:7],"azure1",brewer.pal(11,"RdYlBu")[5:1]),
         annotation_col = anncol,
         scale = "row", #对行数据进行标准化，保留NA
         cluster_rows = T, 
         cluster_cols =F,
         show_rownames = T, 
         show_colnames = F, 
         filename = "pbmc_GSVA_CP.PATHWAYV2.pdf",       
         main = "",width = 15
        )
```


```{r add piegene20220120}
##########################################group120
source("D:/proteomics_library_linda.R")
library(stringr)
library(ggplot2)
library(RColorBrewer)

df_PBMC3 <- read.csv("./df_PBMC3.csv",row.names = 1)
info_PBMCsample2 <- read.csv("./info_PBMCsample2_latest.csv",check.names = F,row.names = 1)

gene_group120 <- read.csv("./PBMC_serum_all_69_adjp.csv",row.names = 1)
gene_group120 <- gene_group120[gene_group120$sample=="PBMC",]
data.node0 <- df_PBMC3[match(gene_group120$DEPs,linda.split(row.names(df_PBMC3),character_pos = 1)),]

heatmap.data <- data.node0

anncol=data.frame(group=info_PBMCsample2$group[match(names(heatmap.data),info_PBMCsample2$MS_ID)]
                  ,label=info_PBMCsample2$TIME[match(names(heatmap.data),info_PBMCsample2$MS_ID)],
                  row.names = names(heatmap.data))

anncol=data.frame(anncol[order(anncol$group),])

anncol$group <- gsub("group1|group2","group12",anncol$group)

centermatrix <- heatmap.data[,row.names(anncol)]
names(centermatrix) <- paste0(anncol$label,"_",anncol$group)

m1  <- data.frame(type=names(centermatrix),t(centermatrix))

##按照每个时间点的group求平均
m1 <- aggregate(m1[,-1],by = list(m1$type),mean,na.rm=T)
centermatrix2 <- t(data.frame(m1[,-1],row.names = m1$Group.1))
data.node <- centermatrix2
##批量画pie
p <- list()
for (i in 1:nrow(data.node)) {
  data_rose = data.frame(data.node[i,])
colnames(data_rose) <- row.names(data.node)[i]
data_rose$group <- row.names(data_rose)
order_group = c("time1_group0","time2_group0","time3_group0","time3_group12","time2_group12","time1_group12")
data_rose <- data_rose[order_group,]
data_rose$group <- factor(x = data_rose$group,levels =  data_rose$group)

data_rose$label = c(rep("group0",3),rep("group12",3))
data_rose$name = c(c("0d","28d","57d"),c("57d","28d","0d"))

p[[i]] <- ggplot(data_rose, aes(group, get(row.names(data.node)[i]),fill = label)) +
  geom_col(width = 1, size=0.8,#bar的边框线粗细
           color="black") + #画bar 
  #geom_col(aes(y = max(data_rose$P49913_CAMP,na.rm = T)),width = 1, alpha = 0.1, color="black",fill = 'white',size = 0) + #人为加外圈园
  geom_hline(aes(yintercept = max(data_rose[,1],na.rm = T)),size=0.8)+ #外圈园半径是最大值
  geom_col(aes(y = 0.2*min(data_rose[,1],na.rm = T)), width = 1, color = 'white', fill = 'white') + #内圈空心园
   scale_fill_manual(values = c("#377EB8","#FF7F00")) +
  coord_polar(direction=-1)+#极坐标转换，逆时针排序
  theme_void() +
  theme(legend.position = "none")
ggsave(paste0(row.names(data.node)[i],"_rosegroup12+0.pdf"),plot = p[[i]],height = 5,width = 5,device = NULL)  
}
##########################################group34
gene_group34 <- read.table("./pielist_group34.txt",sep = "\t",header = F)
data_group34 <- df_PBMC3[gene_group34$V1,row.names(valiprot_matrix4)]

anncol=data.frame(group=info_PBMCsample2$`180d-antigroup`[match(names(data_group34),info_PBMCsample2$MS_ID)]
                  ,label=info_PBMCsample2$TIME[match(names(data_group34),info_PBMCsample2$MS_ID)],
                  row.names = names(data_group34))

anncol=data.frame(anncol[order(anncol$group),])

centermatrix <- data_group34[,row.names(anncol)]
names(centermatrix) <- paste0(anncol$label,"_",anncol$group)

m1  <- data.frame(type=names(centermatrix),t(centermatrix))

##按照每个时间点的group求平均
m1 <- aggregate(m1[,-1],by = list(m1$type),mean,na.rm=T)
centermatrix2 <- t(data.frame(m1[,-1],row.names = m1$Group.1))
data.node <- centermatrix2
##批量画pie

p <- list()
for (i in 1:nrow(data.node)) {
  #i=1
  data_rose = data.frame(data.node[i,])
colnames(data_rose) <- row.names(data.node)[i]
data_rose$group <- row.names(data_rose)
order_group = c("time1_Group3","time2_Group3","time3_Group3","time3_Group4","time2_Group4","time1_Group4")
data_rose <- data_rose[order_group,]
data_rose$group <- factor(x = data_rose$group,levels =  data_rose$group)

data_rose$label = c(rep("Group3",3),rep("Group4",3))
data_rose$name = c(c("0d","28d","57d"),c("57d","28d","0d"))

p[[i]] <- ggplot(data_rose, aes(group, get(row.names(data.node)[i]),fill = label)) +
  geom_col(width = 1, size=0.8,#bar的边框线粗细
           color="black") + #画bar 
  #geom_col(aes(y = max(data_rose$P49913_CAMP,na.rm = T)),width = 1, alpha = 0.1, color="black",fill = 'white',size = 0) + #人为加外圈园
  geom_hline(aes(yintercept = max(data_rose[,1],na.rm = T)),size=0.8)+ #外圈园半径是最大值
  geom_col(aes(y = 0.2*min(data_rose[,1],na.rm = T)), width = 1, color = 'white', fill = 'white') + #内圈空心园
   scale_fill_manual(values = c("#808080","#FF6347")) +
  geom_text(aes(label = name,
                y = data_rose[,1]/2,
                # angle = angle+60
  ),
  nudge_y = 0.2,
  nudge_x = -0.1,
  data = data_rose,
  color = "black",fontface="bold", vjust=1, size = 7)+
  theme(
    panel.background = element_rect( fill = 'white', colour = 'white'),
        #panel.background = element_blank(),
        panel.grid = element_line(colour = "black",
                                          size=0.25,
                                          linetype = "dashed"),
        axis.ticks = element_blank()
        ) +
  coord_polar(direction=-1)+#极坐标转换，逆时针排序
  theme_void() +
  theme(legend.position = "none")
ggsave(paste0(row.names(data.node)[i],"_rosegroup34.pdf"),plot = p[[i]],height = 5,width = 5,device = NULL)  
}
```

```{r pool data}
rm(list = ls())
source("D:/datamining_library_ge.R")
df <- read.csv("./20210715CVDHZ_abundance.csv",row.names=1)
NA_threshold_table(df)
df_pool<- df[,grepl("pool",names(df))]
# batch1 <- ge.split(names(df_pool),"_",1) 
# batch1 <-names(df_pool) 
# write.csv(df_pool,"pool.csv")

df_pool <- df_pool[apply(df_pool,1, function(x){sum(is.na(x))/ncol(df_pool)})<0.9,]
ge.na.ratio(df_pool)
batch1 <-names(df_pool) 

df_pool.matrix <- as.matrix(df_pool)
outlier <-
  (fivenum(df_pool.matrix)[4] - fivenum(df_pool.matrix)[2]) * 2 + fivenum(df_pool.matrix)[4]
df_pool[df_pool > outlier] <- outlier
ge.plot.density(df_pool)


sum.cv <-  apply(df_pool, 1 , function(x) {
        sd(x,na.rm = T) / mean(x,na.rm = T)
      })
median=sprintf("%0.4f",median(sum.cv,na.rm=T))
    df.cv <-
      data.frame(cv = sum.cv, sample = factor(rep("all", each = nrow(df_pool))))
    p <-
      ggplot(df.cv, aes(
        x = sample,
        y = cv,
        color = sample,
        group = sample
      )) +
      scale_color_manual(values=c("#00bFC4"))+
      geom_violin(trim = FALSE) +
      geom_boxplot(width = 0.1) +
      geom_text(aes(0.8,1.5,label = paste0( "median=",median)))+
      theme(
        legend.direction = 'horizontal',
        legend.position = 'top',
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black")
      ) +
      theme(
        axis.text = element_text(size = 15, colour = "black"),
        text = element_text(size = 15, colour = "black")
      ) +
      # theme(axis.text.x = element_text(hjust = 1, angle = 45)) +
      theme(legend.position = "none")
    
    ggsave(
      paste0("pool_CV.pdf"),
      plot = p ,
      device = NULL,
      width = 5,
      height = 5
    )
write.csv(sum.cv,"poolcv.csv")
```



```{r}

df <- read.csv("./20210803CVDHZ_protmatrix_serum.csv",row.names=1)

df <- df[!apply(df,1, function(x){all(is.na(x))}),]
ge.na.ratio(df)

df_pool<- df[,grepl("pool",names(df))]
colnames(df_pool) <- gsub("X.", "", colnames(df_pool))

NA_threshold_table(df_pool)

df_pool <- df_pool[apply(df_pool,1, function(x){sum(is.na(x))/ncol(df_pool)})<0.9,]
ge.na.ratio(df_pool)
batch1 <-names(df_pool) 

df_pool.matrix <- as.matrix(df_pool)
outlier <-
  (fivenum(df_pool.matrix)[4] - fivenum(df_pool.matrix)[2]) * 2 + fivenum(df_pool.matrix)[4]
df_pool[df_pool > outlier] <- outlier
ge.plot.density(df_pool)


sum.cv <-  apply(df_pool, 1 , function(x) {
        sd(x,na.rm = T) / mean(x,na.rm = T)
      })
median=sprintf("%0.4f",median(sum.cv,na.rm=T))
    df.cv <-
      data.frame(cv = sum.cv, sample = factor(rep("pool", each = nrow(df_pool))))
    p <-
      ggplot(df.cv, aes(
        x = sample,
        y = cv,
        color = sample,
        group = sample
      )) +
      geom_violin(trim = FALSE) +
      geom_boxplot(width = 0.1) +
      geom_text(aes(0.8,1.5,label = paste0( "median=",median)))+
      theme(
        legend.direction = 'horizontal',
        legend.position = 'top',
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black")
      ) +
      theme(
        axis.text = element_text(size = 15, colour = "black"),
        text = element_text(size = 15, colour = "black")
      ) +
      # theme(axis.text.x = element_text(hjust = 1, angle = 45)) +
      theme(legend.position = "none")
    
    ggsave(
      paste0("pool_CV_na902.pdf"),
      plot = p ,
      device = NULL,
      width = 5,
      height = 5
    )
write.csv(sum.cv,"poolcv_na902.csv")


```

```{r T}
rm(list = ls())
library(readr)
library(DMwR2)
library(openxlsx)
source("D:/datamining_library_ge.R")

df1 <- read.csv("./20210803CVDHZ_protmatrix_serum.csv",row.names=1)
df1<-df1[,!grepl("pool",names(df1))]
colnames(df1) <- gsub("X.", "", colnames(df1))

ge.na.ratio(df1)
max(df1)

NA_threshold_table(df1)
df1 <- df1[apply(df1,1, function(x){sum(is.na(x))/ncol(df1)})<0.9,]
name<-rownames(df1)
df1=as.data.frame(lapply(df1,as.numeric))
ge.plot.density(df1)
df1.matrix <- as.matrix(df1)
outlier <-
  (fivenum(df1.matrix)[4] - fivenum(df1.matrix)[2]) * 2 + fivenum(df1.matrix)[4]
df1[df1 > outlier] <- outlier
ge.plot.density(df1)
rownames(df1)<-name

batch <- ge.split(names(df1),"_",1) 
batch1 <- batch[!duplicated(batch)]
```

```{r}
id <- read.csv("./CVDHZ_serum_MS_qc.csv")
id <- read.xlsx("./CVDHZ_serum_MS_info0722.xlsx")
id.rep<- id$SampleID[match(colnames(df1),id$MS_ID)]
df2<-df1
colnames(df2)<-id.rep
rownames(df2)<-name
rep <- names(df2)[grepl("_rep", names(df2))]

# df2[is.na(df2)]<- min(df2,na.rm = T)*0.8

df.cor <- c()
for (i in rep) {
  repa <- str_split(i,"_rep")[[1]][1]
  df.r <- df2[,which(names(df2) %in% c(repa,i))]
  # df.r[is.na(df.r)] <- 0
  # new_mean <- apply(df1, 1, function(x){ifelse(sum(is.na(x))==ncol(df1),NA, mean(as.numeric(x),na.rm=T))} )
    cor1 <- as.numeric(df.r[,1])
    cor2 <- as.numeric(df.r[,2])
    r <- cor(cor1, cor2, use = "pairwise.complete.obs")   
    df.cor <- rbind(df.cor,c(repa,r))
}


df11 <- read.csv("./20210715CVDHZ_abundance.csv",row.names=1)
NA_threshold_table(df11)
df11<-df11[,!grepl("pool",names(df11))]
df11 <- df11[apply(df11,1, function(x){sum(is.na(x))/ncol(df11)})<0.9,]

ge.plot.density(df11)
df1.matrix <- as.matrix(df11)
outlier <-
  (fivenum(df1.matrix)[4] - fivenum(df1.matrix)[2]) * 2 + fivenum(df1.matrix)[4]
df11[df11 > outlier] <- outlier


id <- read.xlsx("./CVDHZ_PBMC_MS_info0722.xlsx")
id2.rep<- id$SampleID[match(colnames(df11),id$MS_ID)]
df22<-df11
colnames(df22)<-id2.rep

repB <- names(df22)[grepl("_rep", names(df22))]

df2.cor <- c()
for (i in repB) {
  repa <- str_split(i,"_rep")[[1]][1]
  df.r <- df22[,which(names(df22) %in% c(repa,i))]
  # df.r[is.na(df.r)] <- 0
  # new_mean <- apply(df1, 1, function(x){ifelse(sum(is.na(x))==ncol(df1),NA, mean(as.numeric(x),na.rm=T))} )
    cor1 <- as.numeric(df.r[,1])
    cor2 <- as.numeric(df.r[,2])
    r <- cor(cor1, cor2, use = "pairwise.complete.obs")   
    df2.cor <- rbind(df2.cor,c(repa,r))
}

# df.cor  df2.cor
df.cv <- data.frame(R=as.numeric(c(df2.cor[,2],df.cor[,2])),sample=c(rep("pbmc",each=14),rep("serum",each=3)))

p<-ggplot(df.cv, aes(x = sample, y=R,color=sample)) + 
  scale_y_continuous(limits = c(0,1.05),expand = c(0,0))+
  scale_color_manual(values=c("#00bFC4","#F8766D"))+
  geom_violin(trim=FALSE)+
  scale_fill_manual(values=brewer.pal(12,"Set3")[c(1:10)])+
  geom_boxplot(width=0.1)+
  theme(legend.direction = 'horizontal',legend.position = 'top',panel.grid.major =element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(),axis.line = element_line(colour = "black"))+
 
   theme(axis.text = element_text(size = 15,colour = "black"),text = element_text(size = 15,colour = "black"))+
  theme(axis.text.x = element_text( hjust = 1,angle = 45))+
  theme(legend.position = "none")
 p<-p+annotate("text",x= 2,y=1,size= 4,label= paste0("median = ",round(median(as.numeric(df.cor[,2]),na.rm = T),4)))+annotate("text",x= 1,y=1,size= 4,label= paste0("median = ",round(median(as.numeric(df2.cor[,2]),na.rm = T),4)))
ggsave("T_abundance2.pdf",plot =p ,device = NULL,width = 6, height = 6)

```



```{r QC补充PCA}

info_PBMCsample2 <- read.csv("./info_PBMCsample2_latest.csv")
df_PBMCS <- read.csv("./df_PBMCS0.9.csv",row.names = 1)
df_PBMCS <- df_PBMCS[,!names(df_PBMCS)%in%c("C18_4","C18_5","C18_6")]

df_PBMCgroup34 <- df_PBMCS[,na.omit(info_PBMCsample2$MS_ID[info_PBMCsample2$group!="group0"])]
df_PBMCgroup34 <- df_PBMCgroup34[,!is.na(info_PBMCsample2$X180d.antigroup[match(names(df_PBMCgroup34),info_PBMCsample2$MS_ID)])]

# set.seed(123)
ge.plot.pca(df_PBMCS,type = str_extract(names(df_PBMCS),"C[0-9]*"),title = "PBMC.QC_PCA.ALL",ptColors=ge.color(length(unique(str_extract(names(df_PBMCS),"C[0-9]*")))))

ge.plot.pca(df_PBMCS,type = info_PBMCsample2$group[match(names(df_PBMCS),info_PBMCsample2$MS_ID)],ptColors = c("#87CEFA","#F4A460","#8B4513" ),title = "QC_PCAgroup120")
ge.plot.pca(df_PBMCgroup34,type = info_PBMCsample2$X180d.antigroup[match(names(df_PBMCgroup34),info_PBMCsample2$MS_ID)],ptColors = c("#808080","#FF6347"),title = "QC_PCAgroup34")


```



